language: ruby
rvm:
- 2.1.5
bundler_args: "--without production"
before_install: bundle install
script: rake
deploy:
  provider: heroku
  api_key:
    secure: PTl4SeqAGAOl3NJD0MT11yg+pEkmHtwj0qirRdlNNJ08AgF6lThGe6N+dH3l3JcJRKjlp2Tgt3BtTyKlbejrHuR3QYqswgN5rbrThYVO2yOnteR4VcGso2NiPlIlWTTQb3+QqgMEgwgukOLQgan624DeD2Yt4C4cX+uxV4jQt2Q=
