language: ruby
rvm:
- 2.1.5
bundler_args: "--without production --retry 3"
#bundler_args:
before_install:
  travis_retry bundle install;
  bundle exec rake db:schema:load;
  bundle exec rake db:migrate

#env: DB_MONGO=ds061601.mongolab.com:61601
#     USERNAME_MONGO=test
#     PASSWORD_MONGO=test

script: bundle exec rake
deploy:
  provider: heroku
  app: rails-blog-tutorial
  run:
    - rake db:schema:load
    - rake db:migrate
    - rake db:seed
    - echo "Restarting"
    - restart
  api_key:
    secure: PTl4SeqAGAOl3NJD0MT11yg+pEkmHtwj0qirRdlNNJ08AgF6lThGe6N+dH3l3JcJRKjlp2Tgt3BtTyKlbejrHuR3QYqswgN5rbrThYVO2yOnteR4VcGso2NiPlIlWTTQb3+QqgMEgwgukOLQgan624DeD2Yt4C4cX+uxV4jQt2Q=
cache:
  directories:
  - vendor/bundle

notifications:
  email:
    - david.jimenez19@gmail.com