source 'https://supermarket.chef.io'

cookbook 'apt'
cookbook 'apache2'
cookbook 'git'
cookbook 'sqlite'
cookbook 'vim'
cookbook 'mysql'
cookbook 'mysql2_chef_gem'
cookbook 'postgresql'
cookbook 'nodejs'
cookbook 'build-essential'
cookbook 'ruby_build'
cookbook 'rbenv'
cookbook 'main', path: './chef/site-cookbooks/main'