name             'database'
maintainer       'djimenezc'
maintainer_email 'david.jimenez19@gmail.com'
license          'All rights reserved'
description      'Installs/Configures main'
long_description 'Installs/Configures main'
version          '0.1.0'
default          ''
