name             'database2'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures main'
long_description 'Installs/Configures main'
version          '0.1.0'
depends          'apt', '~> 2.9.2'
depends          'mysql'
depends          'database'
depends          'postgresql'