---
#driver:
#  name: vagrant
#  customize:
#    cableconnected1: 'on'

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04
    driver:
      name: vagrant
      vagrantfile_erb: 'Vagrantfile.erb'
      customize:
          cableconnected1: 'on'

#  - name: ubuntu-14.04
#  - name: centos-7.2

suites:
  - name: default
    run_list:
#      - recipe[apt]
#      - recipe[git::default]
#      - recipe[build-essential]
#      - recipe[learn_chef_apache2::default]
#      - recipe[nodejs::nodejs_from_binary]
#      - recipe[ruby_build]
#      - recipe[rbenv::system]
#      - recipe[rbenv::vagrant]
#      - recipe[main]
      - recipe[database2]
#      - recipe[postinstall]
    attributes:
    verifier:
          inspec_tests:
            - test/recipes
